### ISSUE TITLE
Remove downgrade of the python version in GHA configuration

### ISSUE THREAD

**Issue by kgiusti** [skupperproject/skupper-router#102]
Use the default system version of python instead.

Need to remove [this step](https://github.com/skupperproject/skupper-router/blob/b96b1e792e28fee9347cc51cd3b7bb57aaa986f2/.github/workflows/build.yaml#L99) from the workflow configuration.

**Comment by jiridanek** [comment]
Python 3.6 is the default Python on CentOS 8 as well, so although it is a carryover from Qpid Dispatch, it is still reasonable for skupper-router to test with Python 3.6 as much as possible, because there is a good chance it will be deployed on Python 3.6.

Having said that, CentOS/RHEL 8 offers multiple versions of some packages, and Python is one of those.

```
$ podman run --rm -it ubi8/ubi dnf search 'python3*-devel'
python36-devel.x86_64 : Libraries and header files needed for Python development
python38-devel.x86_64 : Libraries and header files needed for Python development
python39-devel.x86_64 : Libraries and header files needed for Python development
```

Therefore, it would be possible to pick one of the newer Pythons as the required minimum, if there was a good reason. I can think of, in order of importance

1. simply restricting the set of possibilities where there is a little to no benefit of keeping all options open (the logic behind my https://github.com/skupperproject/skupper-router/issues/48)
2. https://www.python.org/dev/peps/pep-0563/ useful feature for tidier type annotations
3. asyncio had few api changes since 3.6, so if that is ever used in testing, it is better to support only recent pythons

**Comment by kgiusti** [comment]
Good point re: Centos8, closing.
