### ISSUE TITLE
system_tests_two_routers failure

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#147]
```
 self = <system_tests_two_routers.TwoRouterTest testMethod=test_07_semantics_closest_is_remote>

    def test_07_semantics_closest_is_remote(self):
        test = SemanticsClosestIsRemote(self.routers[0].addresses[0], self.routers[1].addresses[0])
        test.run()
>       self.assertIsNone(test.error)
E       AssertionError: 'Timeout Expired: sent=100 rcvd=0/0' is not None
```

https://github.com/skupperproject/skupper-router/runs/5481493628?check_suite_focus=true#step:27:133

**Comment by jiridanek** [comment]
There is nothing precisely like this in Dispatch Jira, the closest being https://issues.apache.org/jira/browse/DISPATCH-1782

The timeout errors are now quite common in Skupper, so I assume it is likely caused by parallel test run. For example https://github.com/skupperproject/skupper-router/issues/126#issuecomment-1059764784 is another timeout in different test.

**Comment by jiridanek** [comment]
This timeout can expire even after the -j2 fix, https://github.com/skupperproject/skupper-router/runs/5599813265?check_suite_focus=true#step:26:3782
