### ISSUE TITLE
Rename Dockerfile to Containerfile and remove the dockerfiles folder

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#195]
The Dockerfiles in the dockfiles folder point to qpid-dispatch project and are obsolete. The new Dockerfile is here - https://github.com/skupperproject/skupper-router/blob/main/.github/scripts/Dockerfile

Rename the above Dockerfile to Containerfile

**Comment by jiridanek** [comment]
What about putting the Dockerfile to the top level folder?

**Comment by jiridanek** [comment]
I'm not aware why. I don't see a good reason, I guess @fgiorgetti wanted to tuck it away somewhere.

**Comment by fgiorgetti** [comment]
It can be moved to the top folder. I put it there initially cause the original qpid-dispatch repo already had a Dockerfile
at top level and I wanted to prevent the new one being used as if it was the old one.
But since the original one is gone, it can definitely be moved to top folder and renamed to Containerfile.
