### ISSUE TITLE
🐞 Stuck delivery reported in system_tests_tcp_adaptor.py TcpAdaptorStuckDeliveryTest::test_01_ignore_stuck_deliveries

### ISSUE THREAD

**Issue by jiridanek** [skupperproject/skupper-router#23]
https://github.com/jiridanek/skupper-router/runs/5026451378?check_suite_focus=true#step:27:2618

[TCPStuckDeliveryTest_I1.log](https://github.com/skupperproject/skupper-router/files/7981629/TCPStuckDeliveryTest_I1.log)

```
72: E                   AssertionError: 'Stuck delivery: At least one delivery' unexpectedly found in '2022-02-01 19:03:49.081570 +0000 ROUTER_CORE (info) [C2][L10] Stuck delivery: At least one delivery on this link has been undelivered/unsettled for more than 3 seconds (/home/runner/work/skupper-router/skupper-router/skupper-router/src/router_core/modules/stuck_delivery_detection/delivery_tracker.c:60)\n' : Stuck deliveries should not be logged!
72: 
72: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_tcp_adaptor.py:1119: AssertionError
72: - generated xml file: /__w/skupper-router/skupper-router/skupper-router/build/tests/junitxmls/system_tests_tcp_adaptor.xml -
72: =========================== short test summary info ============================
72: FAILED ::TcpAdaptorStuckDeliveryTest::test_01_ignore_stuck_deliveries - Asser...
72: =================== 1 failed, 9 passed, 2 skipped in 49.22s ====================
35/37 Test #72: system_tests_tcp_adaptor ..........................***Failed   49.43 sec
```

This is something that does not appear to be previously logged in Dispatch Apache Jira.

**Comment by kgiusti** [comment]
Ugh - that's a problem with the test.
The test is supposed to ensure that no TCP-related deliveries are marked as stuck.
The problem here is that the stuck delivery is not a TCP-related delivery (good), but it's a reply delivery for some internal edge communications.  The test should ignore non-TCP stuck deliveries, but there's no way for the test to tell the difference.

I think we can "fix" this test by simplifying the deployment to a single router.  At least that would eliminate other housekeeping traffic.  Or perhaps make the way the test parses the log smarter - determine which links are TCP links and only scan for log messages about them.
