### ISSUE TITLE
system_tests_vflow test failure

### ISSUE THREAD

**Issue by ganeshmurthy** [skupperproject/skupper-router#943]
```

66: ______________ERROR at setup of RouterTest.test_01_attach_far_interior ___________________________________________________
66: 
66: cls = <class 'tests.system_tests_vflow.RouterTest'>
66: 
66:     @classmethod
66:     def setUpClass(cls):
66:         """Start a router"""
66:         super(RouterTest, cls).setUpClass()
66:     
66:         def router(name, connection, connection2=None, mode='interior'):
66:     
66:             config = [
66:                 ('router', {'mode': mode, 'id': name}),
66:                 ('listener', {'port': cls.tester.get_port()}),
66:                 connection
66:             ]
66:     
66:             if connection2:
66:                 config.append(connection2)
66:     
66:             config = Qdrouterd.Config(config)
66:     
66:             cls.routers.append(cls.tester.qdrouterd(name, config, wait=True, cl_args=["-T"]))
66:     
66:         cls.routers = []
66:     
66:         inter_router_port = cls.tester.get_port()
66:         edge_port         = cls.tester.get_port()
66:     
66:         router('A', ('listener', {'role': 'inter-router', 'port': inter_router_port}),
66:                     ('listener', {'role': 'edge', 'port': edge_port}))
66:         router('B', ('connector', {'name': 'connectorToA', 'role': 'inter-router', 'port': inter_router_port}))
66:         router('C', ('connector', {'name': 'connectorToA', 'role': 'edge', 'port': edge_port}), mode='edge')
66:     
66:         cls.routers[0].wait_router_connected('B')
66:         cls.routers[1].wait_router_connected('A')
66: >       cls.routers[0].is_edge_routers_connected()
66: 
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_tests_vflow.py:70: 
66: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:1043: in is_edge_routers_connected
66:     retry(lambda: is_edges_connected(num_edges, num_meshes), **retry_kwargs)
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:151: in retry
66:     ret = function()
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:1043: in <lambda>
66:     retry(lambda: is_edges_connected(num_edges, num_meshes), **retry_kwargs)
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:1020: in is_edges_connected
66:     out = retry_exception(lambda: node.query('io.skupper.router.connection'), delay=1)
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:199: in retry_exception
66:     return function()
66: /home/runner/work/skupper-router/skupper-router/skupper-router/tests/system_test.py:1020: in <lambda>
66:     out = retry_exception(lambda: node.query('io.skupper.router.connection'), delay=1)
66: /home/runner/work/skupper-router/skupper-router/skupper-router/python/skupper_router/management/client.py:284: in query
66:     response = self.call(request)
66: /home/runner/work/skupper-router/skupper-router/skupper-router/python/skupper_router/management/client.py:198: in call
66:     response = self.client.call(request)
66: /opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/proton/_utils.py:620: in call
66:     self.connection.wait(wakeup, msg="Waiting for response")
```
https://github.com/skupperproject/skupper-router/actions/runs/4086380730/jobs/7045839458#step:10:3248

**Comment by ted-ross** [comment]
It times out waiting for the edge router to appear to be connected to the interior.  I believe the timeout is 60 seconds for this check.  If three routers can't sync up in 60 seconds, there's probably a resource shortage in this test.

**Comment by ganeshmurthy** [comment]
This is a slow test system issue. Closing

**Comment by jiridanek** [comment]
@ganeshmurthy we aren't gonna get faster test systems (unless we set up self-hosted gha runner, which might be possible, but not something I'd want to deal with, given that it'd require dealing with infosec team; there are probably guidelines and suggestions (walled off VM shouldn't be too hard to set up and it should be fairly safe should any security breach happen...) but still, I don't want to go this route; there was the Codecov breach, and some GHA breach already, and more are sure to come).

So, I figure we may either 

1. tag the slow (resource intensive) tests and run them separately (either in CMake, or in Python, which is more precise but harder to orchestrate)
2. have some kind of orchestration, such as what's there currently for port numbers, but do it for system resources; have a limit on the concurrent number of routers that can be running and... (well, this would not be as easy as with the ports... but the idea sounded to me promising at first)
3. lower the parallelism in `ctest -j6`, but that will slow _all_ testing in cases where tests work
4. enable rerun-on-failure, report-pass-if-eventually-passed strategy, which feels hacky and people generally dislike it when applied globally (pytest surely supports this), and wouldn't be all that helpful if it required individual tests to be tagged with this (which I am not sure if pytest even supports out of the box)
5. run tests in more than two shards, probably three would do?
6. somehow be able to respond to slow systems by increasing these timeouts on CI, but that risks hiding real issues where the product itself is stuck or too slow (although it is absolutely true that systemtests on GHA is not the correct environment to test for this kind of problems).

Ignoring the problem only makes this type of failures more likely, and each failed CI build is another chore to investigate...

> It times out waiting for the edge router to appear to be connected to the interior. I believe the timeout is 60 seconds for this check. If three routers can't sync up in 60 seconds, there's probably a resource shortage in this test.

@ted-ross That is not true, in CI, `TIMEOUT` should be 300s, because we set it like this,

https://github.com/skupperproject/skupper-router/blob/ad11d05603156ecd0d1ec097047f9e536105d5eb/tests/system_test.py#L141

and in CI, we do

https://github.com/skupperproject/skupper-router/blob/ad11d05603156ecd0d1ec097047f9e536105d5eb/.github/workflows/build.yaml#L219

https://github.com/skupperproject/skupper-router/blob/ad11d05603156ecd0d1ec097047f9e536105d5eb/.github/workflows/build.yaml#L398

**Comment by jiridanek** [comment]
Same problem again, https://github.com/skupperproject/skupper-router/actions/runs/4392626933/jobs/7692577978#step:10:3296

The way this fails is that the setUpClass timeouts (between 14:17:47 and 14:23:33, which is 346 seconds) and then all tests in the class are reported as errored out. Because C router (the edge router) has not connected to router A, but from the order of steps in the test we know routers A and B are at that point connected already.

```
2023-03-11T14:17:47.0878996Z 64: [1mcollecting ... [0mcollected 30 items
2023-03-11T14:17:47.0879831Z 64: 
2023-03-11T14:23:33.7805954Z 64: ::RouterTest::test_01_interior_interior [31mERROR[0m
2023-03-11T14:23:34.8290731Z 64: ::RouterTest::test_02_edge_interior [31mERROR[0m
2023-03-11T14:23:35.8962321Z 64: ::RouterTest::test_03_interior_edge [31mERROR[0m
[...]
```

The first connection attempt to port 25035 (on router A) is the following.

```
2023-03-11 14:17:53.232798 +0000 SERVER (info) [C1] Accepted connection to 0.0.0.0:25035 from 127.0.0.1:48750 (../src/server.c:749)
```

The first to send management query is C9, but that one never gets a reply. The first to get a reply is C10, and the last to do so is C33.

```
2023-03-11 14:18:15.528735 +0000 SERVER (info) [C10] Accepted connection to 0.0.0.0:25035 from 127.0.0.1:60136 (../src/server.c:749)


2023-03-11 14:18:31.684836 +0000 SERVER (info) [C33] Accepted connection to 0.0.0.0:25035 from 127.0.0.1:52336 (../src/server.c:749)
```

C9 is the timeout-exceeded one (still looking into logs for router A)

```
2023-03-11 14:18:15.047065 +0000 SERVER (trace) [C9]: Accepting incoming connection to '0.0.0.0:25035' (../src/server.c:641)

[...]

2023-03-11 14:20:15.068967 +0000 PROTOCOL (trace) [C9]:FRAME: 0 -> @close(24) [error=@error(29) [condition=:"amqp:resource-limit-exceeded", description="local-idle-timeout expired"]] (../src/server.c:111)
2023-03-11 14:20:15.069333 +0000 SERVER (error) [C9] Connection from 127.0.0.1:60126 (to 0.0.0.0:25035) failed: amqp:resource-limit-exceeded local-idle-timeout expired (../src/server.c:1067)
```

## Router C

Here's router C talking to router A, first and last log line in its logs

```
2023-03-11 14:18:06.394723 +0000 SERVER (trace) [C1] Connecting to 127.0.0.1:25034 (../src/server.c:1194)

[...]

2023-03-11 14:18:11.914432 +0000 ROUTER_CORE (info) [C1][L8] Link blocked with zero credit for 5 seconds (../src/router_core/modules/stuck_delivery_detection/delivery_tracker.c:86)
[...]
2023-03-11 14:18:11.914992 +0000 ROUTER_CORE (info) [C1][L20] Link blocked with zero credit for 5 seconds (../src/router_core/modules/stuck_delivery_detection/delivery_tracker.c:86)

[...]

2023-03-11 14:26:29.071308 +0000 PROTOCOL (trace) [C1]:FRAME: 0 <- @flow(19) [next-incoming-id=0xfc, incoming-window=0x7fffffff, next-outgoing-id=0x0, outgoing-window=0x7fffffff, handle=0x0, delivery-count=0xfb, link-credit=0x2, drain=false] (../src/server.c:111)
...

Only thing that strikes me is the timing of the management queries between 14:18:15 and 14:18:31. I somehow would've expected them to last longer...

I'm considering trying that tool from @ChugR on the logs, maybe, if I can figure out how to use it, I can see something helpful there, which would help me summarize for myself what's happening in the test.

Log archive [setUpClass.zip](https://github.com/skupperproject/skupper-router/files/10948882/setUpClass.zip)
